server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/egu_store
    username: root
    password: admin
    driverClassName: com.mysql.cj.jdbc.Driver
jpa:
  show-sql: true
  hibernate:
    ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
