server:
  port: 8080
spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB  # Kích thước tệp tối đa cho mỗi yêu cầu
      max-request-size: 10MB  # Kích thước tối đa của yêu cầu
  datasource:
    url: jdbc:mysql://localhost:3306/egu_store
    username: root
    password: 123456
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
        ddl-auto: none
    properties:
        hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true
jwt:
  expiration: 604800
  secretKey: TBhqQps4YkrQTQ6jJJy5V6+zIbzCtGNSnBAuaIlOmME=
